name: condition workflow
on:
  workflow_dispatch:
  
jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        if: ${{ github.event_name == 'push' }}
        run: echo "The job is running"

    
  
