name: Test Workflow
on:
  workflow_dispatch:

jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.3.0

      - name: Run Test Script
        run: bash src/test.sh

      - name: Print Message
        if: ${{ success() }}
        run: echo "Job is running"

        

  
