name: error-debug Test workflow

on:
  workflow_dispatch:


jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: Check if a file exists
        run: |
          if [[ -f ".github/workflows/config.yml" ]]; then
            echo "::debug:: config.yml file exists"
          else
            echo "::error:: config.yml is missing"
          fi

