on:
  push:
    branches:
      - main
jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        if: ${{ startsWith(github.ref, 'refs/tags/latest') }}
        run: echo "the job is running"
