on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**" 
  pull-request:
    branches:
      - main
      - "release/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.0
      - name: Run tests
        run: npm test

